[Server]
port = 8080
host = "localhost"
base_url = "http://localhost:8008"

[Database]
port = 3306
driver = "mysql"
host = "localhost"
user = "root"
password = "root"
name = "taskflow"

[Crypt]
symmetric_key = "VpDL97pWPbIkSooYc2eQvQdhx84BUbQM"