version: "3.9"

services:
  api:
    build: .
    container_name: taskflow_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config.prod.toml:/app/config.local.toml
    environment:
      - ENV=production
    restart: unless-stopped

  db:
    image: mysql:8.4
    container_name: taskflow_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskflow
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
