[Server]
port = 8067
host = "localhost"
base_url = "http://localhost:8067"

[Database]
port = 3308
driver = "mysql"
host = "localhost"
user = "root"
password = "root"
name = "taskflow"

[Crypt]
symmetric_key = "VpDL97pWPbIkSooYc2eQvQdhx84BUbQM"