[Server]
port = 8080
host = "0.0.0.0"
base_url = "http://localhost:8080"

[Database]
driver = "mysql"
host = "db"
port = 3306
user = "root"
password = "root"
name = "taskflow"

[Crypt]
symmetric_key = "CHANGE_THIS_IN_REAL_PRODUCTION"
